/**
 * Central SEO / site configuration.
 * ================================
 * Single source of truth for canonical URL, titles, descriptions, and
 * social preview content. Imported by `app/layout.tsx`, `app/robots.ts`,
 * `app/sitemap.ts`, `app/manifest.ts`, and the OG image routes so every
 * crawler-facing surface stays in sync.
 *
 * Canonical domain is https://dbrief1.xyz. `NEXT_PUBLIC_SITE_URL` may
 * override it (e.g. staging / preview deploys) — it must be a full origin
 * with no trailing slash.
 */

function resolveSiteUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/+$/, "");
  if (fromEnv) return fromEnv;
  // Vercel preview / branch deploys expose VERCEL_URL without protocol.
  const vercelUrl = process.env.VERCEL_URL?.trim().replace(/\/+$/, "");
  if (vercelUrl) return `https://${vercelUrl}`;
  return "https://dbrief1.xyz";
}

export const siteUrl = resolveSiteUrl();

export const site = {
  name: "Dbrief1",
  shortName: "Dbrief1",
  // <title> default (also used for og:title / twitter:title).
  title: "Dbrief1 — F1 Race Engineering & Strategy Analysis",
  // Title template: child pages render as "<page> | Dbrief1".
  titleTemplate: "%s | Dbrief1",
  // Meta description + og:description + twitter:description + link-preview text.
  description:
    "Dbrief1 turns live timing, telemetry, tyre stints and FIA regulations into clear Formula 1 answers — race strategy, pace analysis and setup insight with interactive charts.",
  tagline: "Race engineering & strategy analysis for Formula 1",
  url: siteUrl,
  locale: "en_US",
  themeColorLight: "#f4f4f5",
  themeColorDark: "#0c0c0c",
  backgroundColor: "#0c0c0c",
  category: "sports",
  creator: "Dbrief1",
  publisher: "Dbrief1",
  keywords: [
    "Formula 1",
    "F1",
    "F1 strategy",
    "F1 race engineering",
    "F1 telemetry analysis",
    "F1 tyre strategy",
    "F1 pace analysis",
    "F1 data analysis",
    "F1 live timing",
    "FIA regulations",
    "Grand Prix strategy",
    "motorsport analytics",
  ],
  // Crawlers fetch these absolute URLs; they are generated by
  // app/opengraph-image.tsx and app/twitter-image.tsx (1200x630 PNG).
  ogImageAlt: "Dbrief1 — F1 race engineering and strategy analysis",
} as const;

export const socialImages = {
  openGraph: `${site.url}/opengraph-image`,
  twitter: `${site.url}/twitter-image`,
} as const;
