name: Deploy FastAPI to Cloud Run

on:
  push:
    paths:
      - "api/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy
        run: |
          gcloud builds submit api \
            --tag gcr.io/f1-api-project/f1-api

          gcloud run deploy f1-api \
            --image gcr.io/f1-api-project/f1-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 1